package j2ee.group01.sportshop.entity;
// Generated Jun 1, 2016 9:27:59 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "sportshop", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class Product implements java.io.Serializable {

	private Integer id;
	private String code;
	private int idCategory;
	private int idAccount;
	private double price;
	private Double pricePromotion;
	private String images;
	private String title;
	private String alias;
	private String description;
	private Double quantity;
	private Date dateCreate;
	private Date dateUpdate;
	private int isActive;
	private Integer isSavedraft;
	private int views;
	private int purchase;

	public Product() {
	}

	public Product(String code, int idCategory, int idAccount, double price, String images, String title, String alias,
			String description, Date dateCreate, Date dateUpdate, int isActive, int views, int purchase) {
		this.code = code;
		this.idCategory = idCategory;
		this.idAccount = idAccount;
		this.price = price;
		this.images = images;
		this.title = title;
		this.alias = alias;
		this.description = description;
		this.dateCreate = dateCreate;
		this.dateUpdate = dateUpdate;
		this.isActive = isActive;
		this.views = views;
		this.purchase = purchase;
	}

	public Product(String code, int idCategory, int idAccount, double price, Double pricePromotion, String images,
			String title, String alias, String description, Double quantity, Date dateCreate, Date dateUpdate,
			int isActive, Integer isSavedraft, int views, int purchase) {
		this.code = code;
		this.idCategory = idCategory;
		this.idAccount = idAccount;
		this.price = price;
		this.pricePromotion = pricePromotion;
		this.images = images;
		this.title = title;
		this.alias = alias;
		this.description = description;
		this.quantity = quantity;
		this.dateCreate = dateCreate;
		this.dateUpdate = dateUpdate;
		this.isActive = isActive;
		this.isSavedraft = isSavedraft;
		this.views = views;
		this.purchase = purchase;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "code", unique = true, nullable = false, length = 4)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "id_category", nullable = false)
	public int getIdCategory() {
		return this.idCategory;
	}

	public void setIdCategory(int idCategory) {
		this.idCategory = idCategory;
	}

	@Column(name = "id_account", nullable = false)
	public int getIdAccount() {
		return this.idAccount;
	}

	public void setIdAccount(int idAccount) {
		this.idAccount = idAccount;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "price_promotion", precision = 22, scale = 0)
	public Double getPricePromotion() {
		return this.pricePromotion;
	}

	public void setPricePromotion(Double pricePromotion) {
		this.pricePromotion = pricePromotion;
	}

	@Column(name = "images", nullable = false, length = 65535)
	public String getImages() {
		return this.images;
	}

	public void setImages(String images) {
		this.images = images;
	}

	@Column(name = "title", nullable = false, length = 65535)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "alias", nullable = false, length = 65535)
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "quantity", precision = 22, scale = 0)
	public Double getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Double quantity) {
		this.quantity = quantity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_create", nullable = false, length = 19)
	public Date getDateCreate() {
		return this.dateCreate;
	}

	public void setDateCreate(Date dateCreate) {
		this.dateCreate = dateCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_update", nullable = false, length = 19)
	public Date getDateUpdate() {
		return this.dateUpdate;
	}

	public void setDateUpdate(Date dateUpdate) {
		this.dateUpdate = dateUpdate;
	}

	@Column(name = "is_active", nullable = false)
	public int getIsActive() {
		return this.isActive;
	}

	public void setIsActive(int isActive) {
		this.isActive = isActive;
	}

	@Column(name = "is_savedraft")
	public Integer getIsSavedraft() {
		return this.isSavedraft;
	}

	public void setIsSavedraft(Integer isSavedraft) {
		this.isSavedraft = isSavedraft;
	}

	@Column(name = "views", nullable = false)
	public int getViews() {
		return this.views;
	}

	public void setViews(int views) {
		this.views = views;
	}

	@Column(name = "purchase", nullable = false)
	public int getPurchase() {
		return this.purchase;
	}

	public void setPurchase(int purchase) {
		this.purchase = purchase;
	}

}
