package j2ee.group01.sportshop.entity;
// Generated Jun 1, 2016 9:27:59 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderDetail generated by hbm2java
 */
@Entity
@Table(name = "request_contact", catalog = "sportshop")
public class RequestContact implements java.io.Serializable {

	private Integer id;
	private String fullname;
	private String email;
	private String content;
	private boolean isRepsonse;
	private Date dateCreate;
	
	public RequestContact() {
	}

	public RequestContact(String fullname, String email, String content, boolean isResponse, Date dateCreate) {
		this.fullname = fullname;
		this.email = email;
		this.content = content;
		this.isRepsonse = isResponse;
		this.dateCreate = dateCreate;
	}
	
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@Column(name = "fullname", nullable = false, length = 65535)
	public String getFullname() {
		return fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}
	@Column(name = "email", nullable = false, length = 65535)
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	@Column(name = "content", nullable = false, length = 65535)
	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "is_repsonse", nullable = false)
	public boolean isRepsonse() {
		return isRepsonse;
	}

	public void setRepsonse(boolean isRepsonse) {
		this.isRepsonse = isRepsonse;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_create", nullable = false, length = 19)
	public Date getDateCreate() {
		return dateCreate;
	}

	public void setDateCreate(Date dateCreate) {
		this.dateCreate = dateCreate;
	}

}
